Practicas\Bundle\Practica1Bundle\Entity\Mensaje:
  type: entity
  table: null
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    nombre:
      type: string
      length: 255
    email:
      type: string
      length: 255
    telefono:
      type: string
      length: 255
    asunto:
      type: string
      length: 255
    mensaje:
      type: string
      length: 255
  lifecycleCallbacks: {  }
