parameters:
#    practica1.example.class: Practicas\Bundle\Practica1Bundle\Example

services:
#    practica1.example:
#        class: %practica1.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
